### ISSUE TITLE
博主，我想跟着你学习一下，是个新手，我该以什么样的顺序或方式去阅读你的源码

### ISSUE THREAD

**Issue by Classical-evil** [CaoGaorong/os-in-rust#2]

**Comment by CaoGaorong** [comment]
如果直接看操作系统源码很难看懂，我建议以下步骤学习：
1. 学习计算机基础，这是手写操作系统的前置知识，包括：
- “计算机组成原理”
- “C语言”
- “汇编”
- “操作系统”
2. 学习手写操作系统，这个可以跟着一些书籍来学习，我推荐：
- 《操作系统真象还原》（教原理的比较多，适合有一定计算机基础的人看）
- 《30天自制操作系统》（不教原理，教小白通俗易懂上手，但是不懂原理直接上手有点云里雾里）
- 《一个64位操作系统的设计与实现》，《操作系统真象还原》是32位的，这本书是64位的
3. 另外还有一些网上开源的操作系统学习项目，比如：
- 清华大学的"rCore"操作系统项目，也是使用Rust手写一个简单的操作系统，不过不是基于x86的
- blog_os项目，基于x86CPU，不过实现地比较基础，只实现到时钟中断就结束了
- 另外也可以看看我本项目写的文档，在语雀上的文档：https://www.yuque.com/caogaorong/xd90rg ，也可以私下加我联系方式，我们可以讨论下
